### ISSUE TITLE
INTERVAL command seems to be unrecognized

### ISSUE THREAD

**Issue by nicof38** [stevearc/dql#11]
Hi,

I'm running 0.5.23 (latest), and while querying "now()", it works fine
As soon as I modify my query to add an interval statement, it fails, even using the one from the documentation (NOW() - INTERVAL("1 day"))

Can you please let me know if interval function is no more supported/working ?

**Comment by stevearc** [comment]
I just did some tests locally using [DynamoDB Local](https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz) and it seems to be working correctly for me.
```
+(localhost:8000) us-west-1> create table foobar (key string hash key, time number range key);
Created table 'foobar'
+(localhost:8000) us-west-1> insert into foobar (key='a', time=now() + interval('1 hour'));
Inserted 1 item
+(localhost:8000) us-west-1> scan * from foobar;
----------------------
| key |     time     |
----------------------
| 'a' | 1504069096.8 |
----------------------
+(localhost:8000) us-west-1> select * from foobar where key='a' and time < now();
No results
:(localhost:8000) us-west-1> select * from foobar where key='a' and time > now();
----------------------
| key |     time     |
----------------------
| 'a' | 1504069096.8 |
----------------------
+(localhost:8000) us-west-1> select * from foobar where key='a' and time > now() + interval('1 day');
No results
:(localhost:8000) us-west-1> select * from foobar where key='a' and time < now() + interval('1 day');
----------------------
| key |     time     |
----------------------
| 'a' | 1504069096.8 |
----------------------
```

Could you give me some more detail about the data that you have in the table and the queries that you're running? You can also put `EXPLAIN` in front of the query and it will tell you the exact API call it's making to DyanamoDB, which should help you debug what's going wrong.
```
+(localhost:8000) us-west-1> explain select * from foobar where key='a' and time < now() + interval('1 day');
query {'ConsistentRead': False,
 'ExpressionAttributeNames': {'#f1': 'key', '#f2': 'time'},
 'ExpressionAttributeValues': {':v1': {'S': u'a'},
                               ':v2': {'N': u'1504152191.041429996490478515625'}},
 'KeyConditionExpression': u'(#f1 = :v1 AND #f2 < :v2)',
 'ReturnConsumedCapacity': 'INDEXES',
 'ScanIndexForward': True,
 'TableName': 'foobar'}
```

**Comment by nicof38** [comment]
Hi,

I've done same test as you and it works fine with a newly created table as describe in your case.

Let's run this one:

eu-west-1> select key,time,now() from foobar where key='a';
----------------------------------------------------------
| key |      time     |              NOW()               |
----------------------------------------------------------
| 'a' | 1504099748.28 | 2017-08-30T12:50:54.388396+00:00 |
----------------------------------------------------------

which is still working but:

eu-west-1> select key,time,now() + interval('1 day') from foobar where key='a';
select key,time,now() + interval('1 day') from foobar where key='a';
                                ^
Expected {{"explain" Group:({{"select" ["consistent"] Group:({"*" | "count(*)" | Group:({Group:(Forward: ...) [Group:({Suppress:("as") variable})]}) 

not working at all and I have the same error in my case even if using this syntax in my where clause.

**Comment by stevearc** [comment]
Ah, this is because I never actually added interval support in the selection part of the statement. So...sorry about that, but it really is a missing feature.

Now when you say that you get "the same error in my case even if using this syntax in my where clause," that probably shouldn't be happening. Could you give me an example of a query where you see that?

**Comment by nicof38** [comment]
Yes, I've been able to reproduce on a sample table and so I think it will be a fetaure request 

Here is the code:
`
eu-west-1> create table tfoobar (key string hash key, time string range key);
Created table 'tfoobar'
eu-west-1> insert into tfoobar (key='b', time='20170831070000');
Inserted 1 item
eu-west-1> scan * from tfoobar;
--------------------------
| key |       time       |
--------------------------
| 'b' | '20170831070000' |
--------------------------
eu-west-1> select key,TS(time) from tfoobar where key='b';
-----------------------------------
| key |      TIMESTAMP(time)      |
-----------------------------------
| 'b' | 2017-08-31T07:00:00+00:00 |
-----------------------------------
eu-west-1> select key,TS(time) from tfoobar where key='b' and MS(TS(time)) > now();
select key,TS(time) from tfoobar where key='a' and MS(TS(time)) > now();
                                               ^
Expected {";" | StringEnd} (at char 47), (line:1, col:48)

`

I think that MS(TS()) is not supported in predicate, even in the select statement, can you confirm ? If so, do you see anyway to filter result based on time when time is a string like this ?

**Comment by stevearc** [comment]
Ah, so here is a limitation that is built in to the database. Dynamo doesn't allow you to transform the data in the index you are querying. If you have the data stored as a string, your query has to be directly compared to those strings. You can't transform them to a timestamp or anything else during your query. Full documentation here: http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html

So the other way to formulate the query that you want is like so:
```
select key,TS(time) from tfoobar where key='b' and time > ms(now());
```

Unfortunately, as you have it right now that will fail because you're trying to compare a string to a number, which Dynamo doesn't like. I would recommend that you instead store your timestamps as a number, as that will be more compact and make comparisons faster and more accurate. Comparing numbers-as-strings is a recipe for unexpected behavior.

```
(localhost:8000) us-west-1> insert into tfoobar (key='b', time='12');
Inserted 1 item
(localhost:8000) us-west-1> select key,TS(time) from tfoobar where key='b' and time < '3';
-----------------------------------
| key |      TIMESTAMP(time)      |
-----------------------------------
| 'b' | 2017-09-12T00:00:00-07:00 |
-----------------------------------
```

That said, if your data is already stored as strings there's not much support from DQL. You probably just won't be able to use the built-in `now()` and `interval` functions since they all assume that you're working with numbers.

**Comment by nicof38** [comment]
Hi,

Yes, my table is designed as is, and so not compatible with DQL and built-in now() and interval().
I've created on AWS a trigger and lambda function to replicate data to a supported format and I can successfully DQL on this one.

Will need now to migrate all the solution to use this table and schema and I will be done. Thanks for your support
